# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
contracts:
  - name: AdminUpgradeabilityProxy
    handler: src/EventHandlers.ts
    events:
      - event: AdminAdded(address indexed account)
      - event: AdminChanged(address previousAdmin, address newAdmin)
      - event: AdminRemoved(address indexed account)
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event: EventMinterAdded(uint256 indexed eventId, address indexed account)
      - event: EventMinterRemoved(uint256 indexed eventId, address indexed account)
      - event: EventToken(uint256 eventId, uint256 tokenId)
      - event: Paused(address account)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: Unpaused(address account)
      - event: Upgraded(address indexed implementation)
networks:
  - id: 1 # Ethereum Mainnet
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${ETHEREUM_MAINNET_ENDPOINT}
  - id: 100 # Gnosis Chain
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${GNOSIS_CHAIN_ENDPOINT}
  - id: 8453 # Base Mainnet
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${BASE_MAINNET_ENDPOINT}
  - id: 42161 # Arbitrum One
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${ARBITRUM_ONE_ENDPOINT}
  - id: 33139 # ApeChain (Not supported by hypersync, so using standard RPC)
    start_block: 6494500 # Approximate block when the contract was deployed (Actual was 6494695 but using a slightly earlier block to be safe)
    rpc: ${APECHAIN_ENDPOINT}
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
  - id: 59144 # Linea
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${LINEA_ENDPOINT}
  - id: 5000 # Mantle
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${MANTLE_ENDPOINT}
  - id: 137 # Polygon Mainnet
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${POLYGON_MAINNET_ENDPOINT}
  - id: 130 # Unichain
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${UNICHAIN_ENDPOINT}
  - id: 88888 # Chiliz Mainnet
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${CHILIZ_MAINNET_ENDPOINT}
  - id: 42220 # Celo Mainnet
    start_block: 0
    contracts:
      - name: AdminUpgradeabilityProxy
        address:
          - 0x22C1f6050E56d2876009903609a2cC3fEf83B415
    rpc: ${CELO_MAINNET_ENDPOINT}
unordered_multichain_mode: true
preload_handlers: true
