services:
  envio-postgres:
    image: postgres:17.5
    restart: always
    ports:
      - "${ENVIO_PG_PORT:-5433}:5432"
    volumes:
      - envio-indexer-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${ENVIO_PG_PASSWORD:-testing}
      POSTGRES_USER: ${ENVIO_PG_USER:-postgres}
      POSTGRES_DB: ${ENVIO_PG_DATABASE:-envio-dev}
    networks:
      - envio-indexer-network
  envio-indexer:
    container_name: envio-indexer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ETHEREUM_MAINNET_ENDPOINT: ${ETHEREUM_MAINNET_ENDPOINT}
        GNOSIS_CHAIN_ENDPOINT: ${GNOSIS_CHAIN_ENDPOINT}
        BASE_MAINNET_ENDPOINT: ${BASE_MAINNET_ENDPOINT}
        ARBITRUM_ONE_ENDPOINT: ${ARBITRUM_ONE_ENDPOINT}
        APECHAIN_ENDPOINT: ${APECHAIN_ENDPOINT:-https://apechain-mainnet.example}
        LINEA_ENDPOINT: ${LINEA_ENDPOINT}
        MANTLE_ENDPOINT: ${MANTLE_ENDPOINT}
        POLYGON_MAINNET_ENDPOINT: ${POLYGON_MAINNET_ENDPOINT}
        UNICHAIN_ENDPOINT: ${UNICHAIN_ENDPOINT}
        CHILIZ_MAINNET_ENDPOINT: ${CHILIZ_MAINNET_ENDPOINT}
        CELO_MAINNET_ENDPOINT: ${CELO_MAINNET_ENDPOINT}
    ports:
      - "127.0.0.1:9898:${ENVIO_INDEXER_PORT:-9898}"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 800M
    restart: always
    environment:
      ENVIO_PG_PASSWORD: ${ENVIO_PG_PASSWORD:-testing}
      ENVIO_PG_HOST: envio-postgres
      ENVIO_PG_PORT: 5432
      ENVIO_PG_USER: ${ENVIO_PG_USER:-postgres}
      ENVIO_PG_DATABASE: ${ENVIO_PG_DATABASE:-envio-dev}
      ENVIO_PG_PUBLIC_SCHEMA: ${ENVIO_PG_PUBLIC_SCHEMA:-envio}
      ENVIO_INDEXER_HOST: 0.0.0.0
      ENVIO_INDEXER_PORT: ${ENVIO_INDEXER_PORT:-9898}
      CONFIG_FILE: ${CONFIG_FILE:-config.yaml}
      LOG_LEVEL: ${LOG_LEVEL:-trace}
      LOG_STRATEGY: ${LOG_STRATEGY:-console-pretty}
      TUI_OFF: ${TUI_OFF:-true}
      ETHEREUM_MAINNET_ENDPOINT: ${ETHEREUM_MAINNET_ENDPOINT}
      GNOSIS_CHAIN_ENDPOINT: ${GNOSIS_CHAIN_ENDPOINT}
      BASE_MAINNET_ENDPOINT: ${BASE_MAINNET_ENDPOINT}
      ARBITRUM_ONE_ENDPOINT: ${ARBITRUM_ONE_ENDPOINT}
      APECHAIN_ENDPOINT: ${APECHAIN_ENDPOINT:-https://apechain-mainnet.example}
      LINEA_ENDPOINT: ${LINEA_ENDPOINT}
      MANTLE_ENDPOINT: ${MANTLE_ENDPOINT}
      POLYGON_MAINNET_ENDPOINT: ${POLYGON_MAINNET_ENDPOINT}
      UNICHAIN_ENDPOINT: ${UNICHAIN_ENDPOINT}
      CHILIZ_MAINNET_ENDPOINT: ${CHILIZ_MAINNET_ENDPOINT}
      CELO_MAINNET_ENDPOINT: ${CELO_MAINNET_ENDPOINT}
      ENVIO_HASURA: false
    healthcheck:
      test: timeout 1s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 5s
      timeout: 2s
      retries: 50
      start_period: 5s
    networks:
      - envio-indexer-network
volumes:
  envio-indexer-storage:
networks:
  envio-indexer-network:
